version: '3.1'

services:

  nginx: 
    image: nginx:stable-alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/CA:/etc/nginx/CA
      - ./${APPD:-app}:/var/www/html
    ports: 
      - 80:80
      - 443:443
    links:
      - php-fpm
  
  php-fpm: 
    image: php:fpm-alpine
    volumes:
      - ./${APPD:-app}:/var/www/html

