version: '3.1'

services:

  nginx: 
    image: nginx:stable-alpine
    networks:
      - nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/CA:/etc/nginx/CA
      - ./${APPD:-app}:/var/www/html
    ports: 
      - 80:80
      - 443:443
    depends_on:
      - php-fpm

  php-fpm:
    image: php:fpm-alpine
    networks:
      - nginx
      - mysql
    volumes:
      - ./${APPD:-app}:/var/www/html

  mysql:
    image: msql:5
    networks:
      - mysql
#     ports:
#       - 3306:3306
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

networks:
  nginx:
  mysql:
