version: '3.1'

services:

  nginx: 
    image: nginx:stable-alpine
    volumes:
      - ./nginx/server.conf:/etc/nginx/conf.d/server.conf
      - ./${APPD:-app}:/var/www/html
    ports: 
      - 80:80
    links:
      - php-fpm
  
  php-fpm: 
    image: php:fpm-alpine
    volumes:
      - ./${APPD:-app}:/var/www/html

